Name:           ros-lunar-ros-control-boilerplate
Version:        0.4.1
Release:        0%{?dist}
Summary:        ROS ros_control_boilerplate package

Group:          Development/Libraries
License:        BSD
URL:            https://github.com/davetcoleman/ros_control_boilerplate
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-actionlib
Requires:       ros-lunar-control-msgs
Requires:       ros-lunar-control-toolbox
Requires:       ros-lunar-controller-manager
Requires:       ros-lunar-hardware-interface
Requires:       ros-lunar-joint-limits-interface
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-rosparam-shortcuts
Requires:       ros-lunar-sensor-msgs
Requires:       ros-lunar-std-msgs
Requires:       ros-lunar-trajectory-msgs
Requires:       ros-lunar-transmission-interface
Requires:       ros-lunar-urdf
BuildRequires:  gflags-devel
BuildRequires:  ros-lunar-actionlib
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-cmake-modules
BuildRequires:  ros-lunar-control-msgs
BuildRequires:  ros-lunar-control-toolbox
BuildRequires:  ros-lunar-controller-manager
BuildRequires:  ros-lunar-hardware-interface
BuildRequires:  ros-lunar-joint-limits-interface
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-rosparam-shortcuts
BuildRequires:  ros-lunar-sensor-msgs
BuildRequires:  ros-lunar-std-msgs
BuildRequires:  ros-lunar-trajectory-msgs
BuildRequires:  ros-lunar-transmission-interface
BuildRequires:  ros-lunar-urdf

%description
Simple simulation interface and template for setting up a hardware interface for
ros_control

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Tue Jun 20 2017 Dave Coleman <davetcoleman@gmail.com> - 0.4.1-0
- Autogenerated by Bloom

* Mon Jun 19 2017 Dave Coleman <davetcoleman@gmail.com> - 0.4.0-0
- Autogenerated by Bloom

