Name:           ros-melodic-ros-control-boilerplate
Version:        0.5.0
Release:        1%{?dist}
Summary:        ROS ros_control_boilerplate package

Group:          Development/Libraries
License:        BSD
URL:            https://github.com/davetcoleman/ros_control_boilerplate
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-actionlib
Requires:       ros-melodic-control-msgs
Requires:       ros-melodic-control-toolbox
Requires:       ros-melodic-controller-manager
Requires:       ros-melodic-hardware-interface
Requires:       ros-melodic-joint-limits-interface
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rosparam-shortcuts
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-trajectory-msgs
Requires:       ros-melodic-transmission-interface
Requires:       ros-melodic-urdf
BuildRequires:  gflags-devel
BuildRequires:  ros-melodic-actionlib
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cmake-modules
BuildRequires:  ros-melodic-control-msgs
BuildRequires:  ros-melodic-control-toolbox
BuildRequires:  ros-melodic-controller-manager
BuildRequires:  ros-melodic-hardware-interface
BuildRequires:  ros-melodic-joint-limits-interface
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-rosparam-shortcuts
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-trajectory-msgs
BuildRequires:  ros-melodic-transmission-interface
BuildRequires:  ros-melodic-urdf

%description
Simple simulation interface and template for setting up a hardware interface for
ros_control

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Wed Sep 18 2019 Dave Coleman <davetcoleman@gmail.com> - 0.5.0-1
- Autogenerated by Bloom

* Thu May 31 2018 Dave Coleman <davetcoleman@gmail.com> - 0.4.1-0
- Autogenerated by Bloom

